version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bip44-constants
    versions:
    - 10.0.0
    - 11.0.0
    - 12.0.0
    - 13.0.0
    - 14.0.0
    - 15.0.0
    - 16.0.0
    - 17.0.0
    - 18.0.0
    - 19.0.0
    - 20.0.0
    - 21.0.0
    - 22.0.0
    - 23.0.0
    - 24.0.0
    - 26.0.0
    - 27.0.0
    - 28.0.0
    - 31.0.0
    - 8.0.100
    - 8.0.101
    - 8.0.102
    - 8.0.103
    - 8.0.92
    - 8.0.93
    - 8.0.95
    - 8.0.96
    - 8.0.97
    - 8.0.98
    - 8.0.99
    - 9.0.0
  - dependency-name: bip39
    versions:
    - 3.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
